MODEL :
  NAME: Discogs-VINet-MIREX-only_train
  ARCHITECTURE: cqtnet
  EMBEDDING_SIZE: 512
  FREQUENCY_BINS: 84
  DOWNSAMPLE_FACTOR: 20 # might try out 3 (like CoverHunter)
  L2_NORMALIZE: True # L2 normalize the embeddings.
  SIMILARITY_SEARCH: MIPS # ['MCSS', 'NNS', 'MIPS'] If L2_NORMALIZE is True, use 'MIPS' for faster search.
  CHECKPOINT_DIR: logs/checkpoints/
  # CONV_CHANNEL: 40
  # NORMALIZATION: bn # ['bn', 'in', 'ibn']
  # POOLING: adaptive_max # ['adaptive_max', 'gem', 'softpool']
  # PROJECTION: linear # ['none', 'linear', 'affine', 'mlp']

TRAIN:
    # Train and Validation, and Augmentation directories
    FEATURES_DIR: /data/audio/mp4/
    TRAIN_CLIQUES: /data/discogs/Discogs-VI-YT-20240701-light.json.train
    VALIDATION_CLIQUES: /data/discogs/Discogs-VI-YT-20240701-light.json.val
    CONTEXT_LENGTH : 8000 # Number of frames to consider as context, before downsampling.
    BATCH_SIZE : 48 # Number of cliques to sample at each iteration. 2 versions per clique is sampled.
    LOSS_CONFIG :
      MARGIN: 0.1 # Triplet loss margin
      POSITIVE_MINING_MODE : random # ['hard', 'random']
      NEGATIVE_MINING_MODE : hard # ['hard', 'random']
      SQUARED_DISTANCE : False # Use squared distance in the loss.
    OPTIMIZER : AdamW # ['SGD', 'Adam', 'AdamW']
    LR:
        INITIAL_RATE: 0.001 # Initial learning rate.
        SCHEDULE : EXPONENTIAL # ['NONE', 'STEP', 'MULTISTEP', 'EXPONENTIAL'].
    DATA_USAGE_RATIO : 1.0 # Fraction of training data to use. Useful for debugging. 1.0 to use 100% of data.