MODEL :
  NAME : Discogs-VINet
  ARCHITECTURE : cqtnet
  CHECKPOINT_DIR: logs/checkpoints/
  DOWNSAMPLE_FACTOR : 20 # Downsampling factor.
  L2_NORMALIZE : True # L2 normalize the embeddings.

TRAIN:
    # Train and Validation, and Augmentation directories
    FEATURES_DIR: /scratch/user/Discogs-VI/features/CQT/cqt/
    TRAIN_CLIQUES: ./data/discogs_20240701/main/Discogs-VI-YT-20240701-light.json.train
    VALIDATION_CLIQUES: ./data/discogs_20240701/main/Discogs-VI-YT-20240701-light.json.val
    CONTEXT_LENGTH : 8000 # Number of frames to consider as context, before downsampling.
    BATCH_SIZE : 48 # Number of cliques to sample at each iteration. 2 versions per clique is sampled.
    LOSS_CONFIG :
      MARGIN: 0.1 # Triplet loss margin
      POSITIVE_MINING_MODE : random # ['hard', 'random']
      NEGATIVE_MINING_MODE : hard # ['hard', 'random']
      SQUARED_DISTANCE : False # Use squared distance in the loss.
    OPTIMIZER : AdamW # ['SGD', 'Adam', 'AdamW']
    LR:
        INITIAL_RATE: 0.001 # Initial learning rate.
        SCHEDULE : EXPONENTIAL # ['NONE', 'STEP', 'MULTISTEP', 'EXPONENTIAL'].
    DATA_USAGE_RATIO : 1.0 # Fraction of training data to use. Useful for debugging. 1.0 to use 100% of data.